[[redirects]]
  from = "https://webo.design/*"
  to = "https://www.webo.agency/:splat"
  status = 301

# Cache Control
[[headers]]
  for = "/static/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/static/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/static/img/*.*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[headers]]
  for = "/static/fonts/*.*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"