[[redirects]]
  from = "https://webo.design/*"
  to = "https://www.webo.agency/:splat"
  status = 301

[[headers]]
  for = "/static/*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/static/*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/static/*.png"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[headers]]
  for = "/static/*.jpg"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[headers]]
  for = "/static/*.gif"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[headers]]
  for = "/static/*.webp"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"