[[redirects]]
  from = "https://webo.design/*"
  to = "https://www.webo.agency/:splat"
  status = 301

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"
    
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"