[[redirects]]
  from = "/.well-known/acme-challenge/*"
  to = "/robots.txt"
  status = 200
  force = true

[[headers]]
  for = "/.well-known/acme-challenge/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Type = "text/plain"

[[redirects]]
  from = "https://webo.design/*"
  to = "https://www.webo.agency/:splat"
  status = 301
