name: Development workflow

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependency
        run: npm install

      - name: Generate website
        run: npm run deploy --if-present

      - name: Deploy to netlify
        id: netlify-deploy
        uses: Triloworld/netlify-action/cli@deploy-output-patch
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
        
      - name: Discord notification
        uses: Ilshidur/action-discord@0.0.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: '${{ toJSON(steps.netlify-deploy) }}'

          
